language: d

os:
 - linux
 - osx

d:
 - dmd
 - ldc

after_success:
 - ./.deploy_docs.sh

env:
 - secure: "Tw0dZnpksI3E21h52Rek3YyO7r92/605WWgFOMuY2/If7ygn4L58jfvTs6zCugpUUNn8cMfUgEULnJtgHhNWZGG+18z+7b+M98jfd1jYkfQX+kOdIoZbkuP1yh0sqW45xfXYDuRqbAFedyeQJl2AGpjG85jdV5NmNcfLsJpT9vLcP6iHJinMQS6KZ1Xd6Izc6xMa6XVrMKeuKb17otMUe8BSsO0xufGNkRMKH4nyjqwlg88giW7x274DmruHeCP5YsId0BEVcehXFufcZ9wYevkzWUKiPvgSGMCJPwzsCHr+Ig19ghwzmDrmscN9TQ/syJveOvtendSWHVV6mWdN2msMS3M68QVgYtuevPQEtZoiis6Re8UoT59MMef8i/srL6k7EQgagmRwTZInvkMXybFG31eJyXHRdTnX28NGqxX7vBzq6nc+HdFTh8Ic4AvL2yLJX++366z//1PiKmcIz7JwLGwjNPJ1eLiFapboTct3i2q13OnhrnfF+4A+6WYm44kt4wbirGGKCCWJ6tjSdgODYAbow0enoFrNa/+LQAlPZ6nOAveQ2Iaahk7UPu4Z3MFPZ4aUJQPMVzpy1kXAxwU7j6+/MiZQCdivdmGf9tuKELQYWs/ctGyUOgZ9ncSV2eWVQ2CcaIucvaQmZ246AZ73DQCvhUreo4v46iJH8LQ="
